# Generated by Django 2.1 on 2020-01-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='category_id',
        ),
    ]
